namespace SpriteKind {
    export const LEFTPADDLES = SpriteKind.create()
    export const RIGHTPADDLES = SpriteKind.create()
}
function CREATE_LEFT_PADDLE () {
    LEFT_PADDLE = sprites.create(img`
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        ..........aaaaa..........
        `, SpriteKind.LEFTPADDLES)
    LEFT_PADDLE.setVelocity(0, 150)
    controller.moveSprite(LEFT_PADDLE)
    LEFT_PADDLE.left = 0
    LEFT_PADDLE.setStayInScreen(true)
}
function CREAR_BOLA () {
    BOLA = sprites.create(img`
        . . . . . b b b b b b . . . . . 
        . . . b b 9 9 9 9 9 9 b b . . . 
        . . b b 9 9 9 9 9 9 9 9 b b . . 
        . b b 9 d 9 9 9 9 9 9 9 9 b b . 
        . b 9 d 9 9 9 9 9 1 1 1 9 9 b . 
        b 9 d d 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 d 9 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 3 9 9 9 9 9 9 9 9 9 1 9 9 b 
        b 5 3 d 9 9 9 9 9 9 9 9 9 9 9 b 
        b 5 3 3 9 9 9 9 9 9 9 9 9 d 9 b 
        b 5 d 3 3 9 9 9 9 9 9 9 d d 9 b 
        . b 5 3 3 3 d 9 9 9 9 d d 5 b . 
        . b d 5 3 3 3 3 3 3 3 d 5 b b . 
        . . b d 5 d 3 3 3 3 5 5 b b . . 
        . . . b b 5 5 5 5 5 5 b b . . . 
        . . . . . b b b b b b . . . . . 
        `, SpriteKind.Player)
    BOLA.setVelocity(100, 100)
    BOLA.setBounceOnWall(true)
    BOLA.y = randint(0, 120)
}
function CREATE_RIGHT_PADDLE () {
    RIGHT_PADDLE = sprites.create(img`
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        ..........88888..........
        `, SpriteKind.RIGHTPADDLES)
    RIGHT_PADDLE.setVelocity(0, 150)
    controller.moveSprite(RIGHT_PADDLE)
    RIGHT_PADDLE.right = 160
    RIGHT_PADDLE.setStayInScreen(true)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.LEFTPADDLES, function (sprite, otherSprite) {
    BOLA.vx = LEFT_PADDLE.vx * -1
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.RIGHTPADDLES, function (sprite, otherSprite) {
    BOLA.vx = RIGHT_PADDLE.vx * -1
    info.player2.changeScoreBy(1)
})
let RIGHT_PADDLE: Sprite = null
let BOLA: Sprite = null
let LEFT_PADDLE: Sprite = null
CREAR_BOLA()
CREATE_LEFT_PADDLE()
CREATE_RIGHT_PADDLE()
